/*
 * MessageParser.cpp
 *
 *  Created on: 2013年10月6日
 *      Author: root
 */

#include "MessageParser.h"

#define ADDMSGBYID(msgid) AddMsg(msgid, new MSG_##msgid);


MessageParser::MessageParser()
{
	AddMsg(C2M_VERIFY_SYN, 						new MSG_C2M_VERIFT_SYN);

	AddMsg(M2C_VERIFY_ACK, 						new MSG_M2C_VERIFY_ACK);

	AddMsg(M2D_PLAYER_BASEINFO_SYN,					new MSG_M2D_PLAYER_BASEINFO_SYN);

	AddMsg(D2M_PLAYER_BASEINFO_ACK,					new MSG_D2M_PLAYER_BASEINFO_ACK);

	AddMsg(C2M_CREATE_PLAYER_SYN,              new MSG_C2M_CREATE_PLAYER_SYN);

	AddMsg(M2D_CREATE_PLAYER_SYN,               new MSG_M2D_CREATE_PLAYER_SYN);

	AddMsg(M2A_VERIFY_ACCOUNT_SYN,             new MSG_M2A_VERIFY_ACCOUNT_SYN);

	AddMsg(A2M_VERIFY_ACCOUNT_ACK,             new MSG_A2M_VERIFY_ACCOUNT_ACK);

	AddMsg(M2A_VERIFY_PAYRESULT_SYN,           new MSG_M2A_VERIFY_PAYRESULT_SYN);

	AddMsg(A2M_VERIFY_PAYRESULT_ACK,           new MSG_A2M_VERIFY_PAYRESULT_ACK);

	AddMsg(M2C_VERIFY_PAYRESULT_ACK,          new MSG_M2C_VERIFY_PAYRESULT_ACK);

	AddMsg(M2A_NOTIFY_PAY_RESULT_ACK,         new MSG_M2A_NOTIFY_PAY_RESULT_ACK);

	AddMsg(C2M_VERIFY_PAYRESULT_SYN,         new MSG_C2M_VERIFY_PAYRESULT_SYN);

	AddMsg(M2D_KEEPALIVE_ACK,						new MSG_M2D_KEEPALIVE_ACK);

	AddMsg(C2M_LOGOUT_SYN,							new MSG_C2M_LOGOUT_SYN);

	AddMsg(C2M_GETCARD_SYN,						new MSG_C2M_GETCARD_SYN);

	AddMsg(M2C_GETCARD_ACK,						new MSG_M2C_GETCARD_ACK);

	AddMsg(C2M_GETCARD_CUTDOWN_SYN,				new MSG_C2M_GETCARD_CUTDOWN_SYN);

	AddMsg(M2C_GETCARD_CUTDOWN_ACK,				new MSG_M2C_GETCARD_CUTDOWN_ACK);

	AddMsg(M2C_CHECK_ACCOUNT,					new MSG_M2C_CHECK_ACCOUNT);

	AddMsg(C2M_UPGRADE_SKILL_SYN,					new MSG_C2M_UPGRADE_SKILL_SYN);

	AddMsg(M2C_UPGRADE_SKILL_ACK,					new MSG_M2C_UPGRADE_SKILL_ACK);

	AddMsg(C2M_SELL_SKILL_SYN,						new MSG_C2M_SELL_SKILL_SYN);

	AddMsg(M2C_SELL_SKILL_ACK,						new MSG_M2C_SELL_SKILL_ACK);

	AddMsg(C2M_UPGRADE_EQUIPMENT_SYN,				new MSG_C2M_UPGRADE_EQUIPMENT_SYN);

	AddMsg(M2C_UPGRADE_EQUIPMENT_ACK,				new MSG_M2C_UPGRADE_EQUIPMENT_ACK);

	AddMsg(C2M_SELL_EQUIPMENT_SYN,					new MSG_C2M_SELL_EQUIPMENT_SYN);

	AddMsg(M2C_SELL_EQUIPMENT_ACK,					new MSG_M2C_SELL_EQUIPMENT_ACK);

	AddMsg(C2M_CONFIGSKILL_SYN,						new MSG_C2M_CONFIGSKILL_SYN);

	AddMsg(M2C_CONFIGSKILL_ACK,						new MSG_M2C_CONFIGSKILL_ACK);

	AddMsg(C2M_CONFIGEQUIPMENT_SYN,					new MSG_C2M_CONFIGEQUIPMENT_SYN);

	AddMsg(M2C_CONFIGEQUIPMENT_ACK,					new MSG_M2C_CONFIGEQUIPMENT_ACK);

	AddMsg(M2D_PLAYERINFO_UPDATE_SYN,				new MSG_M2D_PLAYERINFO_UPDATE_SYN);

	AddMsg(C2M_GETALLRUNESCAPE_SYN,                 new MSG_C2M_RUNESCAPE_INFO);
	AddMsg(M2C_ALLRUNESCAPE_ACK,                    new MSG_M2C_RUNESCAPE_INFO);
	AddMsg(C2M_GETEATCHICHEN_SYN,                   new MSG_C2M_RECOVERY_STATUS_INFO);
	AddMsg(M2C_EATCHICHEN_ACK,                      new MSG_M2C_RECOVERY_STATUS_INFO);
	AddMsg(C2M_GETFIGHT_SYN,                        new MSG_C2M_FIGHT_INFO);
	AddMsg(M2C_FIGHT_ACK,                           new MSG_M2C_FIGHT_RESULT_INFO);
	AddMsg(C2M_GETSERIESFIGHT_SYN,                  new MSG_C2M_SERIES_FIGHT_INFO);
	AddMsg(M2C_SERIESFIGHT_ACK,                     new MSG_M2C_SERIES_FIGHT_RESULTS_INFO);

	AddMsg(C2M_SWAP_FIGHTING_CARD_SYN,			new MSG_C2M_SWAP_FIGHTING_CARD_SYN);
	AddMsg(M2C_SWAP_FIGHTING_CARD_ACK,			new MSG_M2C_SWAP_FIGHTING_CARD_ACK );
	AddMsg(C2M_SWAP_FIGHTING_POSITION_SYN,		new MSG_C2M_SWAP_FIGHTING_POSITION_SYN);
	AddMsg(M2C_SWAP_FIGHTING_POSITION_ACK,		new MSG_M2C_SWAP_FIGHTING_POSITION_ACK);
	AddMsg(C2M_GHOST_RECRUIT_SYN,		new MSG_C2M_GHOST_RECRUIT_SYN);
	AddMsg(M2C_GHOST_RECRUIT_ACK,		new  MSG_M2C_GHOST_RECRUIT_ACK);

	AddMsg(M2D_DUEL_PLAYER_BASEINFO_SYN,			new MSG_M2D_DUEL_PLAYER_BASEINFO_SYN);
	AddMsg(D2M_DUEL_PLAYER_BASEINFO_ACK,			new MSG_D2M_DUEL_PLAYER_BASEINFO_ACK);

	AddMsg(M2D_DUEL_TOPLISTINFO_SYN,				new MSG_M2D_DUEL_TOPLISTINFO_SYN);
	AddMsg(D2M_DUEL_TOPLISTINFO_ACK,				new MSG_D2M_DUEL_TOPLISTINFO_ACK);

	AddMsg(M2D_DUEL_UPDATE_TOPLISTINFO_SYN,			new MSG_M2D_DUEL_UPDATE_TOPLISTINFO_SYN);

	AddMsg(C2M_DUEL_GET_BASEINFO_SYN,				new MSG_C2M_DUEL_GET_BASEINFO_SYN);
	AddMsg(M2C_DUEL_GET_BASEINFO_ACK,				new MSG_M2C_DUEL_GET_BASEINFO_ACK);

	AddMsg(C2M_DUEL_CHALLENGE_SYN,					new MSG_C2M_DUEL_CHALLENGE_SYN);
	AddMsg(M2C_DUEL_CHALLENGE_ACK,					new MSG_M2C_DUEL_CHALLENGE_ACK);

	AddMsg(C2M_DUEL_REFRESH_SCORE_SYN,				new MSG_C2M_DUEL_REFRESH_SCORE_SYN);
	AddMsg(M2C_DUEL_REFRESH_SCORE_ACK,				new MSG_M2C_DUEL_REFRESH_SCORE_ACK);

	AddMsg(C2M_DUEL_EXCHANGE_TRAINING_SYN,			new MSG_C2M_DUEL_EXCHANGE_TRAINING_SYN);
	AddMsg(M2C_DUEL_EXCHANGE_TRAINING_ACK,			new MSG_M2C_DUEL_EXCHANGE_TRAINING_ACK);

	AddMsg(C2M_DUEL_GET_PRIZE_SYN,					new MSG_C2M_DUEL_GET_PRIZE_SYN);
	AddMsg(M2C_DUEL_GET_PRIZE_ACK,					new MSG_M2C_DUEL_GET_PRIZE_ACK);

	AddMsg(M2D_RANK_BLOODYBATTLE_INFO_SYN,			new MSG_M2D_RANK_BLOODYBATTLE_INFO);
	AddMsg(D2M_RANK_BLOODYBATTLE_INFO_ACK,			new MSG_D2M_RANK_BLOODYBATTLE_INFO);

	AddMsg(M2D_RANK_UPDATE_BLOODYBATTLE_INFO_SYN,	new MSG_M2D_RANK_UPDATE_BLOODYBATTLE_INFO);

	AddMsg(D2M_DUEL_TOPLIS_FINISH,					new MSG_D2M_DUEL_TOPLIS_FINISH);

	AddMsg(C2M_BLOODYBATTLE_INFO_SYN,				new MSG_C2M_BLOODYBATTLE_INFO);
	AddMsg(M2C_BLOODYBATTLE_INFO_ACK,				new MSG_M2C_BLOODYBATTLE_INFO);

	AddMsg(C2M_ENTER_BLOODYBATTLE_INFO_SYN,			new MSG_C2M_ENTER_BLOODYBATTLE_INFO);
	AddMsg(M2C_ENTER_BLOODYBATTLE_INFO_ACK,			new MSG_M2C_ENTER_BLOODYBATTLE_INFO);

	AddMsg(C2M_ADDITION_BLOODYBATTLE_INFO_SYN,		new MSG_C2M_ADDITION_BLOODYBATTLE_INFO);
	AddMsg(M2C_ADDITION_BLOODYBATTLE_INFO_ACK,		new MSG_M2C_ADDITION_BLOODYBATTLE_INFO);

	AddMsg(C2M_FIGHT_BLOODYBATTLE_INFO_SYN,			new MSG_C2M_FIGHT_BLOODYBATTLE_INFO);
	AddMsg(M2C_FIGHT_BLOODYBATTLE_INFO_ACK,			new MSG_M2C_FIGHT_BLOODYBATTLE_INFO);

	AddMsg(C2M_RANK_BLOODYBATTLE_INFO_SYN,			new MSG_C2M_RANK_BLOODYBATTLE_INFO);
	AddMsg(M2C_RANK_BLOODYBATTLE_INFO_ACK,			new MSG_M2C_RANK_BLOODYBATTLE_INFO);

	AddMsg(C2M_RANK_BLOODYBATTLE_PLAYER_INFO_SYN,	new MSG_C2M_RANK_BLOODYBATTLE_PLAYER_INFO);
	AddMsg(M2C_RANK_BLOODYBATTLE_PLAYER_INFO_ACK,	new MSG_M2C_RANK_BLOODYBATTLE_PLAYER_INFO);

	AddMsg(C2M_REFRESH_FIGHT_POS_INFO_SYN,			new MSG_C2M_REFRESH_FIGHT_POS_INFO_SYN);
	AddMsg(M2C_REFRESH_FIGHT_POS_INFO_ACK,			new MSG_M2C_REFRESH_FIGHT_POS_INFO_ACK);

	AddMsg(C2M_PASS_EXPERIENCE_SYN,					new MSG_C2M_PASS_EXPERIENCE_SYN);
	AddMsg(M2C_PASS_EXPERIENCE_ACK,					new MSG_M2C_PASS_EXPERIENCE_ACK);

	AddMsg(C2M_CARD_TRAIN_REQUREST_SYN,				new MSG_C2M_CARD_TRAIN_REQUREST_SYN);
	AddMsg(M2C_CARD_TRAIN_REQUREST_ACK,				new MSG_M2C_CARD_TRAIN_REQUREST_ACK);

	AddMsg(C2M_CARD_TRAIN_CONFIRM_SYN,				new MSG_C2M_CARD_TRAIN_CONFIRM_SYN);
	AddMsg(M2C_CARD_TRAIN_CONFIRM_ACK,				new MSG_M2C_CARD_TRAIN_CONFIRM_ACK);

	AddMsg(C2M_BUY_CHALLEGENUM_SYN,					new MSG_C2M_BUY_CHALLEGENUM_INFO);
	AddMsg(M2C_BUY_CHALLEGENUM_ACK,					new MSG_M2C_BUY_CHALLEGENUM_INFO);

	AddMsg(C2M_ITEM_OPEN_BOXORPACKS_SYN,			new MSG_C2M_ITEM_OPEN_BOXORPACKS_SYN);
	AddMsg(M2C_ITEM_OPEN_BOXORPACKS_ACK,			new MSG_M2C_ITEM_OPEN_BOXORPACKS_ACK);

	AddMsg(C2M_ITEM_BUY_SYN,						new MSG_C2M_ITEM_BUY_SYN);
	AddMsg(M2C_ITEM_BUY_ACK,						new MSG_M2C_ITEM_BUY_ACK);

	AddMsg(C2M_CLEAR_CDTIMER_SYN,			new MSG_C2M_CLEAR_CDTIMER_INFO);
	AddMsg(M2C_CLEAR_CDTIMER_ACK,			new MSG_M2C_CLEAR_CDTIMER_INFO);

	AddMsg(C2M_ITEM_USING_SYN,						new MSG_C2M_ITEM_USING_SYN);
	AddMsg(M2C_ITEM_USING_ACK,						new MSG_M2C_ITEM_USING_ACK);

	AddMsg(C2M_ITEM_MARKET_SYN,						new MSG_C2M_ITEM_MARKET_SYN);
	AddMsg(M2C_ITEM_MARKET_ACK,						new MSG_M2C_ITEM_MARKET_ACK);

	AddMsg(C2M_MESSAGESYSTEM_GETALL_SYN,			new MSG_C2M_MESSAGESYSTEM_GETALL_SYN);
	AddMsg(M2C_MESSAGESYSTEM_GETALL_ACK,			new MSG_M2C_MESSAGESYSTEM_GETALL_ACK);

	AddMsg(C2M_MESSAGESYSTEM_INCREMENTAL_SYN,		new MSG_C2M_MESSAGESYSTEM_INCREMENTAL_SYN);

	AddMsg(G2M_MESSAGESYSTEM_ADD_SYN,				new	MSG_G2M_MESSAGESYSTEM_ADD_SYN);
	AddMsg(M2G_MESSAGESYSTEM_ADD_ACK,				new MSG_M2G_MESSAGESYSTEM_ADD_ACK);

	AddMsg(C2M_MESSAGESYSTEM_READ_SYN,				new MSG_C2M_MESSAGESYSTEM_READ_SYN);
	AddMsg(M2C_MESSAGESYSTEM_READ_ACK,				new MSG_M2C_MESSAGESYSTEM_READ_ACK);

	AddMsg(C2M_MESSAGESYSTEM_ACCPETAWARD_SYN,		new MSG_C2M_MESSAGESYSTEM_ACCPETAWARD_SYN);
	AddMsg(M2C_MESSAGESYSTEM_ACCPETAWARD_ACK,		new MSG_M2C_MESSAGESYSTEM_ACCPETAWARD_ACK);

	AddMsg(C2M_MESSAGESYSTEM_TIPS_SYN,				new MSG_C2M_MESSAGESYSTEM_TIPS_SYN);
	AddMsg(M2C_MESSAGESYSTEM_TIPS_ACK,				new MSG_M2C_MESSAGESYSTEM_TIPS_ACK);

	AddMsg(C2M_MESSAGESYSTEM_CHAT_SYN,				new MSG_C2M_MESSAGESYSTEM_CHAT_SYN);
	AddMsg(M2C_MESSAGESYSTEM_CHAT_ACK,				new MSG_M2C_MESSAGESYSTEM_CHAT_ACK);

	AddMsg(M2D_MESSAGESYSTEM_GETALL_SYN,			new MSG_M2D_MESSAGESYSTEM_GETALL_SYN);
	AddMsg(D2M_MESSAGESYSTEM_MAX_MSGID,				new MSG_D2M_MESSAGESYSTEM_MAX_MSGID);
	AddMsg(D2M_MESSAGESYSTEM_GETALL_ACK,			new MSG_D2M_MESSAGESYSTEM_GETALL_ACK);
	AddMsg(D2M_MESSAGESYSTEM_GETALL_FINISH,			new MSG_D2M_MESSAGESYSTEM_GETALL_FINISH);

	AddMsg(M2D_MESSAGESYSTEM_FETCH_SYN,				new MSG_M2D_MESSAGESYSTEM_FETCH_SYN);

	AddMsg(M2D_MESSAGESYSTEM_UPDATE_AWARD_SYN,		new MSG_M2D_MESSAGESYSTEM_UPDATE_AWARD_SYN);
	AddMsg(M2D_MESSAGESYSTEM_UPDATE_CLICK_SYN,		new MSG_M2D_MESSAGESYSTEM_UPDATE_CLICK_SYN);
	AddMsg(M2D_MESSAGESYSTEM_UPDATE_TIPS_SYN,		new MSG_M2D_MESSAGESYSTEM_UPDATE_TIPS_SYN);

	AddMsg(M2L_LOG_SYN,                             new MSG_M2L_LOG_SYN);

	//好友系统
	AddMsg(C2M_REFRESH_FRIENDS_MSG_SYN,				new MSG_C2M_REFRESH_FRIENDS_MSG_SYN);
	AddMsg(M2C_REFRESH_FRIENDS_MSG_ACK,				new MSG_M2C_REFRESH_FRIENDS_MSG_ACK);

	AddMsg(C2M_REFRESH_NEW_FRIENDS_MSG_SYN,			new MSG_C2M_REFRESH_NEW_FRIENDS_MSG_SYN);
	AddMsg(M2C_REFRESH_NEW_FRIENDS_MSG_ACK,			new MSG_M2C_REFRESH_NEW_FRIENDS_MSG_ACK);

	AddMsg(C2M_SEARCH_FRIENDS_SYN,					new MSG_C2M_SEARCH_FRIENDS_SYN);
	AddMsg(M2C_SEARCH_FRIENDS_ACK,					new MSG_M2C_SEARCH_FRIENDS_ACK);

	AddMsg(C2M_INVITE_FRIEND_SYN,					new MSG_C2M_INVITE_FRIEND_SYN);
	AddMsg(M2C_INVITE_FRIEND_ACK,					new MSG_M2C_INVITE_FRIEND_ACK);

	AddMsg(C2M_CONFIRM_INVITE_SYN,					new MSG_C2M_CONFIRM_INVITE_SYN);
	AddMsg(M2C_CONFIRM_INVITE_ACK,					new MSG_M2C_CONFIRM_INVITE_ACK);

	AddMsg(C2M_DELETE_FRIEND_SYN,					new MSG_C2M_DELETE_FRIEND_SYN);
	AddMsg(M2C_DELETE_FRIEND_ACK,					new MSG_M2C_DELETE_FRIEND_ACK);

	AddMsg(C2M_WATCH_FRIEND_FIGHT_POS_SYN,			new MSG_C2M_WATCH_FRIEND_FIGHT_POS_SYN);
	AddMsg(M2C_WATCH_FRIEND_FIGHT_POS_ACK,			new MSG_M2C_WATCH_FRIEND_FIGHT_POS_ACK);

	AddMsg(C2M_MARK_MSG_READ_SYN,					new MSG_C2M_MARK_MSG_READ_SYN);
	AddMsg(M2C_MARK_MSG_READ_ACK,					new MSG_M2C_MARK_MSG_READ_ACK);

	AddMsg(C2M_SEND_MESSAGE_SYN,					new MSG_C2M_SEND_MESSAGE_SYN);
	AddMsg(M2C_SEND_MESSAGE_ACK,					new MSG_M2C_SEND_MESSAGE_ACK);

	AddMsg(M2D_FRIEND_MSG_UPDATE_SYN,				new MSG_M2D_FRIEND_MSG_UPDATE_SYN);

	AddMsg(M2D_PULL_FRIENDS_INFO_SYN,				new MSG_M2D_PULL_FRIENDS_INFO_SYN);
	AddMsg(D2M_PULL_FRIENDS_INFO_ACK,				new MSG_D2M_PULL_FRIENDS_INFO_ACK);
	AddMsg(D2M_PULL_FRIENDS_INFO_FINISH,			new MSG_D2M_PULL_FRIENDS_INFO_FINISH);

	AddMsg(G2G_NOTICE,                              new MSG_G2G_NOTICE);
	AddMsg(G2G_ACCOUNT_AWARD_NOTICE,				new MSG_G2G_ACCOUNT_AWARD_NOTICE);
	AddMsg(G2G_BANNED_PLAYER,                       new MSG_BANNED_PLAYER);
	AddMsg(G2G_GOODS_DISCOUNT,                      new MSG_GOODS_DISCOUNT);
	AddMsg(G2G_DELETE_ANNOUNCEMENT,                 new MSG_G2G_DELETE_ANNOUNCEMENT);

	AddMsg(M2D_ITEM_MARKET_SYN,						new MSG_M2D_ITEM_MARKET_SYN);
	AddMsg(D2M_ITEM_MARKET_ACK,						new MSG_D2M_ITEM_MARKET_ACK);
	AddMsg(M2D_ITEM_UPDATE_MARKET_SYN,				new MSG_M2D_ITEM_UPDATE_MARKET_SYN);

	AddMsg(M2D_BAN_PLAYER_SYN,                          new MSG_M2D_BAN_PLAYER_SYN);
	AddMsg(M2D_BAN_SPEAK_SYN,							new MSG_M2D_BAN_SPEAK_SYN);

	AddMsg(C2M_ANONYMOUS_LOGIN_SYN,               new MSG_C2M_ANONYMOUS_LOGIN_SYN);
	AddMsg(M2C_ANONYMOUS_LOGIN_ACK,               new MSG_M2C_ANONYMOUS_LOG_ACK);
	AddMsg(C2M_PHONE_LOGIN_SYN,                   new MSG_C2M_PHONE_LOGIN_SYN);
	AddMsg(M2C_PHONE_LOGIN_ACK,                   new MSG_M2C_PHONE_LOGIN_ACK);
	AddMsg(M2D_PHONE_LOGIN_SYN,                   new MSG_M2D_PHONE_LOGIN_SYN);
	AddMsg(D2M_PHONE_LOGIN_ACK,                   new MSG_D2M_PHONE_LOGIN_ACK);

	AddMsg(C2M_REGISTER_SYN,                   new MSG_C2M_REGISTER_SYN);
	AddMsg(M2C_REGISTER_ACK,                   new MSG_M2C_REGISTER_ACK);
	AddMsg(M2D_REGISTER_SYN,                   new MSG_M2D_REGISTER_SYN);
	AddMsg(D2M_REGISTER_ACK,                   new MSG_D2M_REGISTER_ACK);

	AddMsg(C2M_BIND_PHONE_SYN,                 new MSG_C2M_BIND_PHONE_SYN);
	AddMsg(M2C_BIND_PHONE_ACK,                 new MSG_M2C_BIND_PHONE_ACK);
	AddMsg(M2D_BIND_PHONE_SYN,                 new MSG_M2D_BIND_PHONE_SYN);
	AddMsg(D2M_BIND_PHONE_ACK,                 new MSG_D2M_BIND_PHONE_ACK);

	AddMsg(A2M_NOTIFY_PAY_RESULT_SYN,           new MSG_A2M_NOTIFY_PAY_RESULT_SYN);

	AddMsg(C2M_GET_ACTIVITY_INFO_SYN,				new MSG_C2M_GET_ACTIVITY_INFO_SYN);
	AddMsg(M2C_GET_ACTIVITY_INFO_ACK,				new MSG_M2C_GET_ACTIVITY_INFO_ACK);
	AddMsg(C2M_GET_RUNNING_OPERATIONG_ACTIVITY_INFO_SYN,new MSG_C2M_GET_RUNNING_OPERATIONG_ACTIVITY_INFO_SYN);
	AddMsg(M2C_GET_RUNNING_OPERATIONG_ACTIVITY_INFO_ACK,new MSG_M2C_GET_RUNNING_OPERATIONG_ACTIVITY_INFO_ACK);
	AddMsg(C2M_RECEIVE_ACTIVITY_UPGRADE_AWARD_SYN,	new MSG_C2M_RECEIVE_ACTIVITY_UPGRADE_AWARD_SYN);
	AddMsg(M2C_RECEIVE_ACTIVITY_UPGRADE_AWARD_ACK,	new MSG_M2C_RECEIVE_ACTIVITY_UPGRADE_AWARD_ACK);
	AddMsg(C2M_RECEIVE_ACTIVITY_HARD_WORK_SYN,		new MSG_C2M_RECEIVE_ACTIVITY_HARD_WORK_SYN);
	AddMsg(M2C_RECEIVE_ACTIVITY_HARD_WORK_ACK,		new MSG_M2C_RECEIVE_ACTIVITY_HARD_WORK_ACK);
	AddMsg(C2M_RECEIVE_CONTINOUS_LOGIN_AWARD_SYN,	new MSG_C2M_RECEIVE_CONTINOUS_LOGIN_AWARD_SYN);
	AddMsg(M2C_RECEIVE_CONTINOUS_LOGIN_AWARD_ACK,	new MSG_M2C_RECEIVE_CONTINOUS_LOGIN_AWARD_ACK);
	AddMsg(C2M_RECEIVE_ACTIVITY_EAT_GINSENG_SYN,	new MSG_C2M_RECEIVE_ACTIVITY_EAT_GINSENG_SYN);
	AddMsg(M2C_RECEIVE_ACTIVITY_EAT_GINSENG_ACK,	new MSG_M2C_RECEIVE_ACTIVITY_EAT_GINSENG_ACK);
	AddMsg(C2M_RECEIVE_ACTIVITY_EIGHT_GRAPH_SYN,	new MSG_C2M_RECEIVE_ACTIVITY_EIGHT_GRAPH_SYN);
	AddMsg(M2C_RECEIVE_ACTIVITY_EIGHT_GRAPH_ACK,	new MSG_M2C_RECEIVE_ACTIVITY_EIGHT_GRAPH_ACK);
	AddMsg(C2M_RECEIVE_ACTIVITY_FORTUNE_SYN,		new MSG_C2M_RECEIVE_ACTIVITY_FORTUNE_SYN);
	AddMsg(M2C_RECEIVE_ACTIVITY_FORTUNE_ACK,		new MSG_M2C_RECEIVE_ACTIVITY_FORTUNE_ACK);
	AddMsg(C2M_ACTIVITY_HARD_WORK_EXPIRED_SYN,		new MSG_C2M_ACTIVITY_HARD_WORK_EXPIRED_SYN);
	AddMsg(M2C_ACTIVITY_HARD_WORK_EXPIRED_ACK,		new MSG_M2C_ACTIVITY_HARD_WORK_EXPIRED_ACK);
	AddMsg(G2M_ACTIVITY_FORTUNE_SET_SYN,            new MSG_G2M_ACTIVITY_FORTUNE_SET_SYN);
	AddMsg(M2G_ACTIVITY_FORTUNE_SET_ACK,            new MSG_M2G_ACTIVITY_FORTUNE_SET_ACK);
	AddMsg(G2G_OPERATION_AC,                        new MSG_G2G_OPERATION_AC);

	AddMsg(C2M_MODIFYNAME_SYN,						new MSG_C2M_MODIFYNAME_SYN);
	AddMsg(M2C_MODIFYNAME_ACK,						new MSG_M2C_MODIFYNAME_ACK);
	AddMsg(M2D_MODIFYNAME_SYN,						new MSG_M2D_MODIFYNAME_SYN);
	AddMsg(D2M_MODIFYNAME_ACK,						new MSG_D2M_MODIFYNAME_ACK);

	AddMsg(C2M_GUIDE_SET_GUIDE_ID_SYN, new MSG_C2M_GUIDE_SET_GUIDE_ID_SYN);
	AddMsg(M2C_GUIDE_SET_GUIDE_ID_ACK, new MSG_M2C_GUIDE_SET_GUIDE_ID_ACK);

	AddMsg(C2M_DUEL_SEND_MESSAGE_SYN, new MSG_C2M_DUEL_SEND_MESSAGE_SYN);
	AddMsg(M2C_DUEL_SEND_MESSAGE_ACK, new MSG_M2C_DUEL_SEND_MESSAGE_ACK);

	AddMsg(C2M_CHECK_GOLD_SYN,         new MSG_C2M_CHECK_GOLD_SYN);
	AddMsg(M2C_CHECK_GOLD_ACK,         new MSG_M2C_CHECK_GOLD_ACK);
	AddMsg(C2M_CHECK_IF_NAME_EXIST_SYN, new MSG_C2M_CHECK_IF_NAME_EXIST_SYN);
	AddMsg(M2C_CHECK_IF_NAME_EXIST_ACK, new MSG_M2C_CHECK_IF_NAME_EXIST_ACK);
	AddMsg(M2D_CHECK_IF_NAME_EXIST_SYN, new MSG_M2D_CHECK_IF_NAME_EXIST_SYN);
	AddMsg(D2M_CHECK_IF_NAME_EXIST_ACK, new MSG_D2M_CHECK_IF_NAME_EXIST_ACK);

	AddMsg(C2M_VERIFY_CODE_SYN,         new MSG_C2M_VERIFY_CODE_SYN);
	AddMsg(M2C_VERIFY_CODE_ACK,         new MSG_M2C_VERIFY_CODE_ACK);
	AddMsg(M2A_VERIFY_CODE_SYN,         new MSG_M2A_VERIFY_CODE_SYN);
	AddMsg(A2M_VERIFY_CODE_ACK,         new MSG_A2M_VERIFY_CODE_ACK);
	AddMsg(M2A_ACQUIRE_CODE_SYN,        new MSG_M2A_ACQUIRE_CODE_SYN);
	AddMsg(A2M_ACQUIRE_CODE_ACK,        new MSG_A2M_ACQUIRE_CODE_ACK);
	AddMsg(A2M_PHONE_LOGIN_ACK,         new MSG_A2M_PHONE_LOGIN_ACK);
	AddMsg(M2A_PHONE_LOGIN_SYN,         new MSG_M2A_PHONE_LOGIN_SYN);

	AddMsg(C2M_VERIFY_IOS_PAY_RESULT_SYN, new MSG_C2M_VERIFY_IOS_PAY_RESULT_SYN);
	AddMsg(M2C_VERIFY_IOS_PAY_RESULT_ACK, new MSG_M2C_VERIFY_IOS_PAY_RESULT_ACK);
	AddMsg(M2A_VERIFY_IOS_PAY_RESULT_SYN, new MSG_M2A_VERIFY_IOS_PAY_RESULT_SYN);
	AddMsg(A2M_VERIFY_IOS_PAY_RESULT_ACK, new MSG_A2M_VERIFY_IOS_PAY_RESULT_ACK);
	AddMsg(M2C_CHECK_CDKEY_ACK,           new MSG_M2C_CHECK_CDKEY_ACK);
	AddMsg(C2M_CHECK_CDKEY_SYN,           new MSG_C2M_CHECK_CDKEY_SYN);
	AddMsg(M2A_CHECK_CDKEY_SYN,           new MSG_M2A_CHECK_CDKEY_SYN);
	AddMsg(A2M_CHECK_CDKEY_ACK,           new MSG_A2M_CHECK_CDKEY_ACK);
	AddMsg(C2M_GET_SERVERLIST_SYN,        new MSG_C2M_GET_SERVERLIST_SYN);
	AddMsg(M2C_GET_SERVERLIST_ACK,        new MSG_M2C_GET_SERVERLIST_ACK);

	AddMsg(C2M_LADDER_FETCH_CONTEXT_SYN, new MSG_C2M_LADDER_FETCH_CONTEXT_SYN);
	AddMsg(M2C_LADDER_FETCH_CONTEXT_ACK, new MSG_M2C_LADDER_FETCH_CONTEXT_ACK);
	AddMsg(C2M_LADDER_FIND_ENEMY_SYN, new MSG_C2M_LADDER_FIND_ENEMY_SYN);
	AddMsg(M2C_LADDER_FIND_ENEMY_ACK, new MSG_M2C_LADDER_FIND_ENEMY_ACK);
	AddMsg(C2M_LADDER_FIGHT_SYN, new MSG_C2M_LADDER_FIGHT_SYN);
	AddMsg(M2C_LADDER_FIGHT_ACK, new MSG_M2C_LADDER_FIGHT_ACK);
	AddMsg(C2M_LADDER_FIGHT_BACK_SYN, new MSG_C2M_LADDER_FIGHT_BACK_SYN);
	AddMsg(M2C_LADDER_FIGHT_BACK_ACK, new MSG_M2C_LADDER_FIGHT_BACK_ACK);
	AddMsg(C2M_LADDER_FETCH_RANK_LIST_SYN, new MSG_C2M_LADDER_FETCH_RANK_LIST_SYN);
	AddMsg(M2C_LADDER_FETCH_RANK_LIST_ACK, new MSG_M2C_LADDER_FETCH_RANK_LIST_ACK);
	AddMsg(C2M_LADDER_REDUCE_FATIGUE_SYN, new MSG_C2M_LADDER_REDUCE_FATIGUE_SYN);
	AddMsg(M2C_LADDER_REDUCE_FATIGUE_ACK, new MSG_M2C_LADDER_REDUCE_FATIGUE_ACK);

	AddMsg(M2D_LADDER_FETCH_PLAYER_SYN, new MSG_M2D_LADDER_FETCH_PLAYER_SYN);
	AddMsg(D2M_LADDER_FETCH_PLAYER_ACK, new MSG_D2M_LADDER_FETCH_PLAYER_ACK);
	AddMsg(D2M_LADDER_FETCH_PLAYER_FIN, new MSG_D2M_LADDER_FETCH_PLAYER_FIN);
	AddMsg(M2D_LADDER_FETCH_RANK_LIST_SYN, new MSG_M2D_LADDER_FETCH_RANK_LIST_SYN);
	AddMsg(D2M_LADDER_FETCH_RANK_LIST_ACK, new MSG_D2M_LADDER_FETCH_RANK_LIST_ACK);
	AddMsg(D2M_LADDER_FETCH_RANK_LIST_FIN, new MSG_D2M_LADDER_FETCH_RANK_LIST_FIN);
	AddMsg(M2D_LADDER_UPDATE_PLAYER_SYN, new MSG_M2D_LADDER_UPDATE_PLAYER_SYN);
	AddMsg(M2D_LADDER_UPDATE_RANK_LIST_SYN, new MSG_M2D_LADDER_UPDATE_RANK_LIST_SYN);

	AddMsg(C2M_LADDER_OTHERPLAYER_FIGHTINGPOS_SYN,new MSG_C2M_LADDER_OTHERPLAYER_FIGHTINGPOS_SYN);
	AddMsg(M2C_LADDER_OTHERPLAYER_FIGHTINGPOS_ACK,new MSG_M2C_LADDER_OTHERPLAYER_FIGHTINGPOS_ACK);
	AddMsg(C2M_LADDER_EXCHANGE_COIN_SYN,new MSG_C2M_LADDER_EXCHANGE_COIN_SYN);
	AddMsg(M2C_LADDER_EXCHANGE_COIN_ACK,new MSG_M2C_LADDER_EXCHANGE_COIN_ACK);
    AddMsg(C2M_LADDER_FETCH_FIGHT_BACK_ENEMY_SYN,new MSG_C2M_LADDER_FETCH_FIGHT_BACK_ENEMY_SYN);
    AddMsg(M2C_LADDER_FETCH_FIGHT_BACK_ENEMY_ACK,new MSG_M2C_LADDER_FETCH_FIGHT_BACK_ENEMY_ACK);

	ADDMSGBYID(C2M_ADD_APPRENTICE_SYN)
	ADDMSGBYID(M2C_ADD_APPRENTICE_ACK)
	ADDMSGBYID(M2D_ADD_APPRENTICE_SYN)
	ADDMSGBYID(D2M_ADD_APPRENTICE_ACK)
	ADDMSGBYID(M2A_ADD_APPRENTICE_SYN)
	ADDMSGBYID(A2M_ADD_APPRENTICE_ACK)

	ADDMSGBYID(C2M_GET_APPRENTICE_SYN)
	ADDMSGBYID(M2C_GET_APPRENTICE_ACK)
	ADDMSGBYID(M2A_GET_APPRENTICE_SYN)
	ADDMSGBYID(A2M_GET_APPRENTICE_ACK)

	ADDMSGBYID(C2M_DEL_APPRENTICE_SYN)
	ADDMSGBYID(M2C_DEL_APPRENTICE_ACK)
	ADDMSGBYID(M2A_DEL_APPRENTICE_SYN)
	ADDMSGBYID(A2M_DEL_APPRENTICE_ACK)
	ADDMSGBYID(C2M_GET_APPRENTICE_AWARD_SYN)
	ADDMSGBYID(M2C_GET_APPRENTICE_AWARD_ACK)
	ADDMSGBYID(M2A_GET_APPRENTICE_AWARD_SYN)
	ADDMSGBYID(A2M_GET_APPRENTICE_AWARD_ACK)

	ADDMSGBYID(G2G_GM_SET_PLAYER_INFO_SYN)

	ADDMSGBYID(C2M_MISSION_UPDATE_CHECK_SYN)
	ADDMSGBYID(M2C_MISSION_UPDATA_CHECK_ACK)
	ADDMSGBYID(C2M_MISSION_FETCH_INFO_SYN)
	ADDMSGBYID(M2C_MISSION_FETCH_INFO_ACK)
	ADDMSGBYID(C2M_MISSION_AWARD_ACQUIRE_SYN)
	ADDMSGBYID(M2C_MISSION_AWARD_ACQUIRE_ACK)

	ADDMSGBYID(C2M_REFRESH_MYSTERY_SHOP_INFO_SYN)
	ADDMSGBYID(M2C_REFRESH_MYSTERY_SHOP_INFO_ACK)

	ADDMSGBYID(C2M_BUY_MYSTERY_GOOD_SYN)
	ADDMSGBYID(M2C_BUY_MYSTERY_GOOD_ACK)

	ADDMSGBYID(C2M_GET_FRIENDS_INVITE_STATUS_SYN)
	ADDMSGBYID(M2C_GET_FRIENDS_INVITE_STATUS_ACK)

	ADDMSGBYID(M2A_JIUYOU_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_JIUYOU_SDK_LOGIN_ACK)
	ADDMSGBYID(C2M_JIUYOU_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_JIUYOU_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_DANGLE_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_DANGLE_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_DANGLE_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_DANGLE_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_91_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_91_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_91_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_91_SDK_LOGIN_ACK)


	ADDMSGBYID(C2M_DUOKU_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_DUOKU_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_DUOKU_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_DUOKU_SDK_LOGIN_ACK)


	ADDMSGBYID(C2M_360_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_360_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_360_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_360_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_ANZHI_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_ANZHI_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_ANZHI_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_ANZHI_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_HUAWEI_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_HUAWEI_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_HUAWEI_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_HUAWEI_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_XIAOMI_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_XIAOMI_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_XIAOMI_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_XIAOMI_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_91_IOS_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_91_IOS_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_91_IOS_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_91_IOS_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_QQ_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_QQ_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_QQ_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_QQ_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_WANDOUJIA_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_WANDOUJIA_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_WANDOUJIA_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_WANDOUJIA_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_TONGBUTUI_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_TONGBUTUI_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_TONGBUTUI_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_TONGBUTUI_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_PPHELPER_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_PPHELPER_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_PPHELPER_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_PPHELPER_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_OPPO_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_OPPO_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_OPPO_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_OPPO_SDK_LOGIN_ACK)

	ADDMSGBYID(C2M_COMMON_SDK_LOGIN_SYN)
	ADDMSGBYID(M2C_COMMON_SDK_LOGIN_ACK)
	ADDMSGBYID(M2A_COMMON_SDK_LOGIN_SYN)
	ADDMSGBYID(A2M_COMMON_SDK_LOGIN_ACK)

	ADDMSGBYID(M2D_GET_COSUME_RANK_BILLBOARD_SYN)
	ADDMSGBYID(D2M_GET_COSUME_RANK_BILLBOARD_ACK)
	ADDMSGBYID(M2D_UPDATE_COSUME_RANK_BILLBOARD)



	AddMsg(CTRL_CMD, new MSG_CTRL_CMD);

	AddMsg(C2M_LADDER_FRIENDCARDS_SYN,	new MSG_C2M_LADDER_FRIENDCARDS_SYN);
	AddMsg(M2C_LADDER_FRIENDCARDS_ACK,	new MSG_M2C_LADDER_FRIENDCARDS_ACK);

	AddMsg(C2M_GM_SET_PLAYER_INFO_SYN,new MSG_C2M_GM_SET_PLAYER_INFO_SYN);

	AddMsg(C2M_CARD_UPGRADE_QUALITY_SYN,new MSG_C2M_CARD_UPGRADE_QUALITY_SYN);
	AddMsg(M2C_CARD_UPGRADE_QUALITY_ACK,new MSG_M2C_CARD_UPGRADE_QUALITY_ACK);

	AddMsg(M2A_COMMON_PUSH_MSG_SYN,new MSG_M2A_COMMON_PUSH_MSG_SYN);

	AddMsg(C2M_BUY_POWER_SYN, new MSG_C2M_BUY_POWER_SYN);
	AddMsg(M2C_BUY_POWER_ACK, new MSG_M2C_BUY_POWER_ACK);

	AddMsg(C2M_GET_VIPCARD_INFO_SYN,new MSG_C2M_GET_VIPCARD_INFO_SYN);
	AddMsg(M2C_GET_VIPCARD_INFO_ACK,new MSG_M2C_GET_VIPCARD_INFO_ACK);

	AddMsg(C2M_GET_VIPCARD_DAYPRIZE_SYN,new MSG_C2M_GET_VIPCARD_DAYPRIZE_SYN);
	AddMsg(M2C_GET_VIPCARD_DAYPRIZE_ACK,new MSG_M2C_GET_VIPCARD_DAYPRIZE_ACK);

	AddMsg(C2M_GET_EQUIPFRAG_INFO_SYN,new MSG_C2M_GET_EQUIPFRAG_INFO_SYN);
	AddMsg(M2C_GET_EQUIPFRAG_INFO_ACK,new MSG_M2C_GET_EQUIPFRAG_INFO_ACK);

	AddMsg(C2M_MERGE_FRAG_TO_EQUIP_SYN,new MSG_C2M_MERGE_FRAG_TO_EQUIP_SYN);
	AddMsg(M2C_MERGE_FRAG_TO_EQUIP_ACK,new MSG_M2C_MERGE_FRAG_TO_EQUIP_ACK);


	AddMsg(C2M_UPGRADE_GEMSTONE_SYN,new MSG_C2M_UPGRADE_GEMSTONE_SYN);
	AddMsg(M2C_UPGRADE_GEMSTONE_ACK,new MSG_M2C_UPGRADE_GEMSTONE_ACK);

	AddMsg(C2M_MERGE_GEMSTONE_SYN,new MSG_C2M_MERGE_GEMSTONE_SYN);
	AddMsg(M2C_MERGE_GEMSTONE_ACK,new MSG_M2C_MERGE_GEMSTONE_ACK);

	AddMsg(C2M_DECOMPOSITE_GEMSTONE_SYN,new MSG_C2M_DECOMPOSITE_GEMSTONE_SYN);
	AddMsg(M2C_DECOMPOSITE_GEMSTONE_ACK,new MSG_M2C_DECOMPOSITE_GEMSTONE_ACK);

	AddMsg(C2M_EQUIP_DIGHOLE_SYN,new MSG_C2M_EQUIP_DIGHOLE_SYN);
	AddMsg(M2C_EQUIP_DIGHOLE_ACK,new MSG_M2C_EQUIP_DIGHOLE_ACK);

	AddMsg(C2M_EQUIP_EMBED_GEMSTONE_SYN,new MSG_C2M_EQUIP_EMBED_GEMSTONE_SYN);
	AddMsg(M2C_EQUIP_EMBED_GEMSTONE_ACK,new MSG_M2C_EQUIP_EMBED_GEMSTONE_ACK);

	AddMsg(C2M_EQUIP_REMOVE_GEMSTONE_SYN,new MSG_C2M_EQUIP_REMOVE_GEMSTONE_SYN);
	AddMsg(M2C_EQUIP_REMOVE_GEMSTONE_ACK,new MSG_M2C_EQUIP_REMOVE_GEMSTONE_ACK);

	AddMsg(C2M_GET_DYNAMICRUNE_INFO_SYN,new MSG_C2M_GET_DYNAMICRUNE_INFO_SYN);
	AddMsg(M2C_GET_DYNAMICRUNE_INFO_ACK,new MSG_M2C_GET_DYNAMICRUNE_INFO_ACK);

	AddMsg(C2M_FIGHT_DYNAMICRUNE_SYN,new MSG_C2M_FIGHT_DYNAMICRUNE_INFO_SYN);
	AddMsg(M2C_FIGHT_DYNAMICRUNE_ACK,new MSG_M2C_FIGHT_DYNAMICRUNE_INFO_ACK);

	AddMsg(C2M_SERFIGHT_DYNAMICRUNE_SYN,new MSG_C2M_SERFIGHT_DYNAMICRUNE_INFO_SYN);
	AddMsg(M2C_SERFIGHT_DYNAMICRUNE_ACK,new MSG_M2C_SERFIGHT_DYNAMICRUNE_INFO_ACK);

	AddMsg(C2M_GET_CHECKIN_INFO_SYN,new MSG_C2M_GET_CHECKIN_INFO_SYN);
	AddMsg(M2C_GET_CHECKIN_INFO_ACK,new MSG_M2C_GET_CHECKIN_INFO_ACK);

	AddMsg(C2M_CHECKIN_SYN,new MSG_C2M_CHECKIN_SYN);
	AddMsg(M2C_CHECKIN_ACK,new MSG_M2C_CHECKIN_ACK);

	AddMsg(C2M_HERO_JUEDI_GET_INFO_SYN,new MSG_C2M_HERO_JUEDI_GET_INFO_SYN);
	AddMsg(M2C_HERO_JUEDI_GET_INFO_ACK,new MSG_M2C_HERO_JUEDI_GET_INFO_ACK);

	AddMsg(C2M_HERO_JUEDI_FIGHT_SYN,new MSG_C2M_HERO_JUEDI_FIGHT_SYN);
	AddMsg(M2C_HERO_JUEDI_FIGHT_ACK,new MSG_M2C_HERO_JUEDI_FIGHT_ACK);

	AddMsg(C2M_HERO_JUEDI_FIGHT_ALL_SYN,new MSG_C2M_HERO_JUEDI_FIGHT_ALL_SYN);
	AddMsg(M2C_HERO_JUEDI_FIGHT_ALL_ACK,new MSG_M2C_HERO_JUEDI_FIGHT_ALL_ACK);

	AddMsg(C2M_HERO_JUEDI_ADD_FIGHTING_NUM_SYN,new MSG_C2M_HERO_JUEDI_ADD_FIGHTING_NUM_SYN);
	AddMsg(M2C_HERO_JUEDI_ADD_FIGHTING_NUM_ACK,new MSG_M2C_HERO_JUEDI_ADD_FIGHTING_NUM_ACK);

	AddMsg(C2M_HERO_ATTRIBUTE_GET_INFO_SYN,new MSG_C2M_HERO_ATTRIBUTE_GET_INFO_SYN);
	AddMsg(M2C_HERO_ATTRIBUTE_GET_INFO_ACK,new MSG_M2C_HERO_ATTRIBUTE_GET_INFO_ACK);

	AddMsg(C2M_HERO_ATTRIBUTE_UPGRADE_SYN,new MSG_C2M_HERO_ATTRIBUTE_UPGRADE_SYN);
	AddMsg(M2C_HERO_ATTRIBUTE_UPGRADE_ACK,new MSG_M2C_HERO_ATTRIBUTE_UPGRADE_ACK);

	AddMsg(C2M_GET_TREASURE_INFO_SYN,new MSG_C2M_GET_TREASURE_INFO_SYN);
	AddMsg(M2C_GET_TREASURE_INFO_ACK,new MSG_M2C_GET_TREASURE_INFO_ACK);

	AddMsg(C2M_START_TREASURE_SYN,new MSG_C2M_START_TREASURE_SYN);
	AddMsg(M2C_START_TREASURE_ACK,new MSG_M2C_START_TREASURE_ACK);

	AddMsg(C2M_EXPLORER_TREASURE_SYN,new MSG_C2M_EXPLORER_TREASURE_SYN);
	AddMsg(M2C_EXPLORER_TREASURE_ACK,new MSG_M2C_EXPLORER_TREASURE_ACK);

	AddMsg(C2M_BUY_TREASURE_SYN,new MSG_C2M_BUY_TREASURE_SYN);
	AddMsg(M2C_BUY_TREASURE_ACK,new MSG_M2C_BUY_TREASURE_ACK);

	AddMsg(C2M_REVIVE_TREASURE_SYN,new MSG_C2M_REVIVE_TREASURE_SYN);
	AddMsg(M2C_REVIVE_TREASURE_ACK,new MSG_M2C_REVIVE_TREASURE_ACK);

	AddMsg(C2M_FINGER_TREASURE_SYN,new MSG_C2M_FINGER_TREASURE_SYN);
	AddMsg(M2C_FINGER_TREASURE_ACK,new MSG_M2C_FINGER_TREASURE_ACK);

	AddMsg(C2M_INVITATION_CODE_GET_INFO_SYN , new MSG_C2M_INVITATION_CODE_GET_INFO_SYN );
	AddMsg(M2C_INVITATION_CODE_GET_INFO_ACK , new MSG_M2C_INVITATION_CODE_GET_INFO_ACK );
	AddMsg(M2A_INVITATION_CODE_GET_INFO_SYN , new MSG_M2A_INVITATION_CODE_GET_INFO_SYN );
	AddMsg(A2M_INVITATION_CODE_GET_INFO_ACK , new MSG_A2M_INVITATION_CODE_GET_INFO_ACK );

	AddMsg(C2M_INVITATION_CODE_AWARD_SYN , new MSG_C2M_INVITATION_CODE_AWARD_SYN );
	AddMsg(M2C_INVITATION_CODE_AWARD_ACK , new MSG_M2C_INVITATION_CODE_AWARD_ACK );
	AddMsg(M2A_INVITATION_CODE_AWARD_SYN , new MSG_M2A_INVITATION_CODE_AWARD_SYN );
	AddMsg(A2M_INVITATION_CODE_AWARD_ACK , new MSG_A2M_INVITATION_CODE_AWARD_ACK );

	AddMsg(C2M_INVITATION_CODE_CONFIRM_CANCEL_SYN , new MSG_C2M_INVITATION_CODE_CONFIRM_CANCEL_SYN );
	AddMsg(M2C_INVITATION_CODE_CONFIRM_CANCEL_ACK , new MSG_M2C_INVITATION_CODE_CONFIRM_CANCEL_ACK );
	AddMsg(M2A_INVITATION_CODE_CONFIRM_CANCEL_SYN , new MSG_M2A_INVITATION_CODE_CONFIRM_CANCEL_SYN );
	AddMsg(A2M_INVITATION_CODE_CONFIRM_CANCEL_ACK , new MSG_A2M_INVITATION_CODE_CONFIRM_CANCEL_ACK );

	AddMsg(C2M_INVITATION_CODE_INPUT_SYN , new MSG_C2M_INVITATION_CODE_INPUT_SYN );
	AddMsg(M2C_INVITATION_CODE_INPUT_ACK , new MSG_M2C_INVITATION_CODE_INPUT_ACK );
	AddMsg(M2A_INVITATION_CODE_INPUT_SYN , new MSG_M2A_INVITATION_CODE_INPUT_SYN );
	AddMsg(A2M_INVITATION_CODE_INPUT_ACK , new MSG_A2M_INVITATION_CODE_INPUT_ACK );

	AddMsg(C2M_INVITATION_CODE_DELETE_SYN , new MSG_C2M_INVITATION_CODE_DELETE_SYN );
	AddMsg(M2C_INVITATION_CODE_DELETE_ACK , new MSG_M2C_INVITATION_CODE_DELETE_ACK );
	AddMsg(M2A_INVITATION_CODE_DELETE_SYN , new MSG_M2A_INVITATION_CODE_DELETE_SYN );
	AddMsg(A2M_INVITATION_CODE_DELETE_ACK , new MSG_A2M_INVITATION_CODE_DELETE_ACK );

	AddMsg(C2M_GET_EXPAND_INFO_SYN, new MSG_C2M_GET_EXPAND_INFO_SYN );
	AddMsg(M2C_GET_EXPAND_INFO_ACK, new MSG_M2C_GET_EXPAND_INFO_ACK );

	AddMsg(C2M_LADDER_OPERATION_FIGHTINGPOS_SYN,new MSG_C2M_LADDER_OPERATION_FIGHTINGPOS_SYN);
	AddMsg(M2C_LADDER_OPERATION_FIGHTINGPOS_ACK,new MSG_M2C_LADDER_OPERATION_FIGHTINGPOS_ACK);

	AddMsg(M2D_LADDER_FIGHTINGPOS_GET_FRIENDS_CARD_INFO_SYN,new MSG_M2D_LADDER_FIGHTINGPOS_GET_FRIENDS_CARD_INFO_SYN);
	AddMsg(D2M_LADDER_FIGHTINGPOS_GET_FRIENDS_CARD_INFO_ACK,new MSG_D2M_LADDER_FIGHTINGPOS_GET_FRIENDS_CARD_INFO_ACK);

	AddMsg(C2M_CONSUME_RANK_INFO_SYN, new MSG_C2M_CONSUME_RANK_INFO_SYN);
	AddMsg(M2C_CONSUME_RANK_INFO_ACK, new MSG_M2C_CONSUME_RANK_INFO_ACK);

	AddMsg(C2M_CONSUME_RANK_BILLBOARD_INFO_SYN, new MSG_C2M_CONSUME_RANK_BILLBOARD_INFO_SYN);
	AddMsg(M2C_CONSUME_RANK_BILLBOARD_INFO_ACK, new MSG_M2C_CONSUME_RANK_BILLBOARD_INFO_ACK);

	AddMsg(C2M_CONSUME_RANK_AWARD_INFO_SYN, new MSG_C2M_CONSUME_RANK_AWARD_INFO_SYN);
	AddMsg(M2C_CONSUME_RANK_AWARD_INFO_ACK, new MSG_M2C_CONSUME_RANK_AWARD_INFO_ACK);

	AddMsg(G2G_BUSINESS_ACTIVITY_OPENSERVER_NOTICE, new MSG_G2G_BUSINESS_ACTIVITY_OPENSERVER_NOTICE);
	AddMsg(G2G_BUSINESS_ACTIVITY_INIT, new MSG_G2G_BUSINESS_ACTIVITY_INIT);
	AddMsg(G2G_BUSINESS_ACTIVITY_GETCARD, new MSG_G2G_BUSINESS_ACTIVITY_GETCARD);
	AddMsg(G2G_BUSINESS_ACTIVITY_OPENBOX, new MSG_G2G_BUSINESS_ACTIVITY_OPENBOX);
	AddMsg(G2G_BUSINESS_ACTIVITY_CONSUMERANK, new MSG_G2G_BUSINESS_ACTIVITY_CONSUMERANK);

	AddMsg(C2M_ITEM_ADD_PLAYER_OR_FIGHTCARD_EXP_SYN,new MSG_C2M_ITEM_ADD_PLAYER_OR_FIGHTCARD_EXP_SYN);
	AddMsg(M2C_ITEM_ADD_PLAYER_OR_FIGHTCARD_EXP_ACK,new MSG_M2C_ITEM_ADD_PLAYER_OR_FIGHTCARD_EXP_ACK);
	AddMsg(C2M_ITEM_ADD_ONE_CARD_EXP_SYN,new MSG_C2M_ITEM_ADD_ONE_CARD_EXP_SYN);
	AddMsg(M2C_ITEM_ADD_ONE_CARD_EXP_ACK,new MSG_M2C_ITEM_ADD_ONE_CARD_EXP_ACK);
}

MessageParser::~MessageParser()
{
	std::map< unsigned short,::google::protobuf::Message* >::iterator iter;
	::google::protobuf::Message* pMsg;

	for(iter = m_messages.begin();iter != m_messages.end();++iter)
	{
		pMsg = iter->second;
		if(pMsg)
		{
			delete pMsg;
		}
	}

	m_messages.clear();
}

void MessageParser::AddMsg(unsigned short protoid,::google::protobuf::Message* pMsg)
{
	if(!pMsg)
	{
		return;
	}

	m_messages.insert(std::make_pair(protoid,pMsg));
}

::google::protobuf::Message* MessageParser::FetchMessage(unsigned short protoid)
{

	std::map< unsigned short,::google::protobuf::Message* >::iterator iter = m_messages.find(protoid);

	if(iter == m_messages.end())
	{
		return NULL;
	}

	::google::protobuf::Message* message = iter->second;

	if (message != NULL)
	{
		message->Clear();
	}

	return message;
}

